# Root directory for storing all artifacts generated during the process
artifacts_root: artifacts

# Configuration for data ingestion
data_ingestion:
  root_dir: artifacts/data_ingestion 
  source_URL: https://drive.google.com/file/d/1bWXyzdW44RCxZQeH3PAJ4MDvStAZre2d/view?usp=sharing 
  local_data_file: artifacts/data_ingestion/data.zip  
  unzip_dir: artifacts/data_ingestion 


# Configuration for preparing the base model
prepare_base_model:
  root_dir: artifacts/prepare_base_model 
  base_model_path: artifacts/prepare_base_model/base_model.h5 
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5 

# Configuration for training the model
training:
  root_dir: artifacts/training  
  trained_model_path: artifacts/training/model.h5 
  